name: cd
on:
  workflow_dispatch:
  check_run:
    types:
      - completed

jobs:
  maven-cd:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: CrimsonCustomJenkins/reusable-actions/checkout@main
        with:
          java-version: 21
      - name: Publish
        uses: CrimsonCustomJenkins/jenkins-maven-cd-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
