name: Build and Test

on:
  push:
    paths:
      - "**/*.java"
      - "**/pom.xml"
    branches:
      - "master"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Build
        run: |
          mvn --no-transfer-progress --batch-mode clean install
          mvn package
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-${{ github.run_id }}
          path: target/
          overwrite: true
          retention-days: 3
        continue-on-error: true